### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [shahriar-ratul/test-api-web-keyword#1]
Hello Atik 👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and I will be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

> [!NOTE]
> I might open issues on the other respoitory (https://github.com/shahriar-ratul/test-api-web-keyword) if needed.

**Comment by olivierobert** [comment]
I have now wrapped up the initial code review round. I have focused on the most critical issues to ensure we can keep the code review within the allotted time. I am now waiting for your feedback on the open issues 🙏

**Comment by olivierobert** [comment]
I have reviewed the PRs you opened and added comments. 

The code review is going slower than expected. Since it has 2 days and only one day is left, please share how you would tackle the issue I am more interested in your approach than having a fix prepared.

**Comment by shahriar-ratul** [comment]
Thanks for your review. 

yes sorry for The code review is going slower.i will share my code today.

i am sharing my approach how i will fix other issue.

* Asynchronous processing of keywords in this one. i will add queue job. store csv in memory like public/csv folder.
then the job will do process csv store data in database and get scrap data from google.

* Increase test coverage here i will add Integration Testing for CSV parsing ,Keyword creation ,Keyword scraping ,Keyword listing.

**Comment by olivierobert** [comment]
I have now complete the final round of code reviews. I invite you to review the latest comments. Thank you @shahriar-ratul for your efforts 🙏 We have now sufficient information to finalize our assessment. So I will wrap up this code review and coordinate with the talent team to provide you with feedback on the next step.
